### ISSUE TITLE
OTP 20.3 TLS/SSL problem

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp#85]
There seems to be a problem with OTP 20.3, not present in previous OTP 20 versions.

When this is solved, add 20.3 to the travis ci matrix.

```
=INFO REPORT==== 29-Jun-2018::05:09:20 ===
TLS client: In state certify at ssl_handshake.erl:1295 generated CLIENT ALERT: Fatal - Handshake Failure - {bad_cert,hostname_check_failed}
ssl_tests: successful_ssl_connect_test (module 'ssl_tests')...*skipped*
undefined
*unexpected termination of test process*
::{failed_to_upgrade_socket,{tls_alert,"handshake failure"}}
```

**Comment by getong** [comment]
I think it is fixed in #84 , but there is still logger problem in erlang 21. I will fix it in a few days.

**Comment by getong** [comment]
It can be closed now.

**Comment by DenysGonchar** [comment]
this issue is still valid and it's reproducible only on OTP 20.3. please see [travis report](https://travis-ci.org/DenysGonchar/mysql-otp/jobs/542374424)
```
ssl_tests: successful_ssl_connect_test (module 'ssl_tests')...
=INFO REPORT==== 6-Jun-2019::17:08:19 ===
TLS client: In state certify at tls_connection.erl:739 generated CLIENT ALERT: Fatal - Handshake Failure - malformed_handshake_data
*skipped*
undefined
*unexpected termination of test process*
::{failed_to_upgrade_socket,{tls_alert,"handshake failure"}}
```

**Comment by zuiderkwast** [comment]
OK, obviously there's a TLS error. I think this is related to some bug in OTP 20.3. Perhaps it's works in OTP 20.3 with different ssl options? I don't know if it's possible to solve here, but we can at least document it. It would be good to link this one to an OTP bug report or similar.
