### ISSUE TITLE
OTP 21 compatibility

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp#86]
The following problems needs to be addressed:

* Warnings for deprecated function `erlang:get_stacktrace()`. Probably we should use `catch C:E:T` for OTP 21 and `get_stacktrace` for older versions, using `-ifdef` rules.
* The tests for expected errors, where a custom error handler is used to capture errors from the error logger and then check that we got the errors we expected, seem to be broken. This is possibly due to the introduction of the new `logger` and the changed implementation of `error_logger`.

**Comment by getong** [comment]
There is a bug in erlang 21 binary matching, we will need to wait for it.
```
decode_binary(_, <<Length, Data/binary>>) ->
    %% Coded in the same way as DATETIME and TIMESTAMP below, but returned in
    %% a simple triple.

    case {Length, Data} of
        {0, _} -> io:format("~p length:~p, Data:~p, ~n" , [?LINE, Length, Data]),{{0, 0, 0}, Data};
        {4, <<Y:16/little, M, D, Rest/binary>>} -> io:format("~p~n" , [?LINE]),{{Y, M, D}, Rest}
    end.

```
The `decode_binary(not_care, <<0>>) ` function return `{{0,0,0}, <<0>>}`
But it should return `{{0,0,0}, <<>>}`.
```
<<Length, Data/binary>> = <<0>>.
Data = <<>>.
```

**Comment by zuiderkwast** [comment]
Thanks @getong! I found the bug you created here: https://bugs.erlang.org/browse/ERL-689

**Comment by zuiderkwast** [comment]
Update: It is being solved in OTP: https://github.com/erlang/otp/pull/1911

**Comment by getong** [comment]
The bug is still remained on some point, I reopen the issue, and add test code.
But the code seems to work.

**Comment by getong** [comment]
It can be closed now.

**Comment by getong** [comment]
see erlang/otp#1967

**Comment by erdii** [comment]
Not sure about that...

I use `mysqlex` which is based on `mysql-otp` with OTP 20.3.8.8 and it works just fine, but not with newer versions.

**Comment by zuiderkwast** [comment]
I guess your version of mysqlex is not using the latest version of mysql-otp where this issue is fixed.

**Comment by erdii** [comment]
Yikes, thanks!
